code_path = [
    'utils.py',
    'attribute_tagger_pyfunc.py',
    'product_config.py'
]


colors_list = ['absolute zero',
 'acid green',
 'aero',
 'aero blue',
 'african violet',
 'air superiority blue',
 'alabaster',
 'alizarin',
 'alice blue',
 'alloy orange',
 'almond',
 'amaranth',
 'amaranth (m&p)',
 'amaranth pink',
 'amaranth purple',
 'amaranth red',
 'amazon',
 'amber',
 'amber (sae/ece)',
 'amethyst',
 'android green',
 'antique brass',
 'antique bronze',
 'antique fuchsia',
 'antique ruby',
 'antique white',
 'ao (english)',
 'apple green',
 'apricot',
 'aqua',
 'aquamarine',
 'arctic lime',
 'army green',
 'artichoke',
 'arylide yellow',
 'ash gray',
 'asparagus',
 'astronaut',
 'atomic tangerine',
 'auburn',
 'aureolin',
 'avocado',
 'azure',
 'azure (x11/web color)',
 'baby blue',
 'baby blue eyes',
 'baby pink',
 'baby powder',
 'baker-miller pink',
 'banana mania',
 'barbie pink',
 'barn red',
 'battleship grey',
 'beau blue',
 'beaver',
 'beige',
 "b'dazzled blue",
 'big dip o’ruby',
 'bisque',
 'bistre',
 'bistre brown',
 'bitter lemon',
 'bitter lime',
 'bittersweet',
 'bittersweet shimmer',
 'black',
 'black bean',
 'black chocolate',
 'black coffee',
 'black coral',
 'black olive',
 'black shadows',
 'blanched almond',
 'blast-off bronze',
 'bleu de france',
 'blizzard blue',
 'blond',
 'blood red',
 'blue',
 'blue (crayola)',
 'blue (munsell)',
 'blue (ncs)',
 'blue (pantone)',
 'blue (pigment)',
 'blue (ryb)',
 'blue bell',
 'blue-gray',
 'blue-green',
 'blue-green (color wheel)',
 'blue jeans',
 'blue sapphire',
 'blue-violet',
 'blue-violet (crayola)',
 'blue-violet (color wheel)',
 'blue yonder',
 'bluetiful',
 'blush',
 'bole',
 'bone',
 'bottle green',
 'brandy',
 'brick red',
 'bright green',
 'bright lilac',
 'bright maroon',
 'bright navy blue',
 'bright yellow (crayola)',
 'brilliant rose',
 'brink pink',
 'british racing green',
 'bronze',
 'brown',
 'brown sugar',
 'brunswick green',
 'bud green',
 'buff',
 'burgundy',
 'burlywood',
 'burnished brown',
 'burnt orange',
 'burnt sienna',
 'burnt umber',
 'byzantine',
 'byzantium',
 'cadet',
 'cadet blue',
 'cadet blue (crayola)',
 'cadet grey',
 'cadmium green',
 'cadmium orange',
 'cadmium red',
 'cadmium yellow',
 'café au lait',
 'café noir',
 'cambridge blue',
 'camel',
 'cameo pink',
 'canary',
 'canary yellow',
 'candy apple red',
 'candy pink',
 'capri',
 'caput mortuum',
 'cardinal',
 'caribbean green',
 'carmine',
 'carmine (m&p)',
 'carnation pink',
 'carnelian',
 'carolina blue',
 'carrot orange',
 'castleton green',
 'catawba',
 'cedar chest',
 'celadon',
 'celadon blue',
 'celadon green',
 'celeste',
 'celtic blue',
 'cerise',
 'cerulean',
 'cerulean blue',
 'cerulean frost',
 'cerulean (crayola)',
 'cg blue',
 'cg red',
 'champagne',
 'champagne pink',
 'charcoal',
 'charleston green',
 'charm pink',
 'chartreuse (traditional)',
 'chartreuse (web)',
 'cherry blossom pink',
 'chestnut',
 'chili red',
 'china pink',
 'china rose',
 'chinese red',
 'chinese violet',
 'chinese yellow',
 'chocolate (traditional)',
 'chocolate (web)',
 'chocolate cosmos',
 'chrome yellow',
 'cinereous',
 'cinnabar',
 'cinnamon satin',
 'citrine',
 'citron',
 'claret',
 'cobalt blue',
 'cocoa brown',
 'coffee',
 'columbia blue',
 'congo pink',
 'cool grey',
 'copper',
 'copper (crayola)',
 'copper penny',
 'copper red',
 'copper rose',
 'coquelicot',
 'coral',
 'coral pink',
 'cordovan',
 'corn',
 'cornell red',
 'cornflower blue',
 'cornsilk',
 'cosmic cobalt',
 'cosmic latte',
 'coyote brown',
 'cotton candy',
 'cream',
 'crimson',
 'crimson (ua)',
 'crystal',
 'cultured',
 'cyan',
 'cyan (process)',
 'cyber grape',
 'cyber yellow',
 'cyclamen',
 'dark blue-gray',
 'dark brown',
 'dark byzantium',
 'dark cornflower blue',
 'dark cyan',
 'dark electric blue',
 'dark goldenrod',
 'dark green',
 'dark green (x11)',
 'dark jungle green',
 'dark khaki',
 'dark lava',
 'dark liver',
 'dark liver (horses)',
 'dark magenta',
 'dark moss green',
 'dark olive green',
 'dark orange',
 'dark orchid',
 'dark pastel green',
 'dark purple',
 'dark red',
 'dark salmon',
 'dark sea green',
 'dark sienna',
 'dark sky blue',
 'dark slate blue',
 'dark slate gray',
 'dark spring green',
 'dark turquoise',
 'dark violet',
 'dartmouth green',
 "davy's grey",
 'deep cerise',
 'deep champagne',
 'deep chestnut',
 'deep jungle green',
 'deep pink',
 'deep saffron',
 'deep sky blue',
 'deep space sparkle',
 'deep taupe',
 'denim',
 'denim blue',
 'desert',
 'desert sand',
 'dim gray',
 'dodger blue',
 'dogwood rose',
 'drab',
 'duke blue',
 'dutch white',
 'earth yellow',
 'ebony',
 'ecru',
 'eerie black',
 'eggplant',
 'eggshell',
 'egyptian blue',
 'eigengrau',
 'electric blue',
 'electric green',
 'electric indigo',
 'electric lime',
 'electric purple',
 'electric violet',
 'emerald',
 'eminence',
 'english green',
 'english lavender',
 'english red',
 'english vermillion',
 'english violet',
 'erin',
 'eton blue',
 'fallow',
 'falu red',
 'fandango',
 'fandango pink',
 'fashion fuchsia',
 'fawn',
 'feijoa',
 'feldgrau',
 'fern green',
 'field drab',
 'fiery rose',
 'finn',
 'firebrick',
 'fire engine red',
 'fire opal',
 'flame',
 'flax',
 'flirt',
 'floral white',
 'fluorescent blue',
 'forest green (crayola)',
 'forest green (traditional)',
 'forest green (web)',
 'french beige',
 'french bistre',
 'french blue',
 'french fuchsia',
 'french lilac',
 'french lime',
 'french mauve',
 'french pink',
 'french raspberry',
 'french rose',
 'french sky blue',
 'french violet',
 'frostbite',
 'fuchsia',
 'fuchsia (crayola)',
 'fuchsia purple',
 'fuchsia rose',
 'fulvous',
 'fuzzy wuzzy',
 'gainsboro',
 'gamboge',
 'generic viridian',
 'ghost white',
 'glaucous',
 'glossy grape',
 'go green',
 'gold',
 'gold (metallic)',
 'gold (web) (golden)',
 'gold (crayola)',
 'gold fusion',
 'golden brown',
 'golden poppy',
 'golden yellow',
 'goldenrod',
 'gotham green',
 'granite gray',
 'granny smith apple',
 'gray (web)',
 'gray (x11 gray)',
 'green',
 'green (crayola)',
 'green (web)',
 'green (munsell)',
 'green (ncs)',
 'green (pantone)',
 'green (pigment)',
 'green (ryb)',
 'green-blue',
 'green-blue (crayola)',
 'green-cyan',
 'green lizard',
 'green sheen',
 'green-yellow',
 'green-yellow (crayola)',
 'shades of red#grenadier',
 'grullo',
 'gunmetal',
 'han blue',
 'han purple',
 'hansa yellow',
 'harlequin',
 'harvest gold',
 'heat wave',
 'heliotrope',
 'heliotrope gray',
 'hollywood cerise',
 'honeydew',
 'honolulu blue',
 "hooker's green",
 'hot magenta',
 'hot pink',
 'hunter green',
 'iceberg',
 'icterine',
 'illuminating emerald',
 'imperial red',
 'inchworm',
 'independence',
 'india green',
 'indian red',
 'indian yellow',
 'indigo',
 'indigo dye',
 'infrared',
 'international klein blue',
 'international orange (aerospace)',
 'international orange (engineering)',
 'international orange (golden gate bridge)',
 'iris',
 'irresistible',
 'isabelline',
 'italian sky blue',
 'ivory',
 'jade',
 'japanese carmine',
 'japanese violet',
 'jasmine',
 'jazzberry jam',
 'jet',
 'jonquil',
 'june bud',
 'jungle green',
 'kelly green',
 'keppel',
 'key lime',
 'khaki (web)',
 'khaki (x11) (light khaki)',
 'kobe',
 'kobi',
 'kobicha',
 'kombu green',
 'ksu purple',
 'languid lavender',
 'lapis lazuli',
 'laser lemon',
 'laurel green',
 'lava',
 'lavender (floral)',
 'lavender (web)',
 'lavender blue',
 'lavender blush',
 'lavender gray',
 'lawn green',
 'lemon',
 'lemon chiffon',
 'lemon curry',
 'lemon glacier',
 'lemon meringue',
 'lemon yellow',
 'lemon yellow (crayola)',
 'liberty',
 'light blue',
 'light coral',
 'light cornflower blue',
 'light cyan',
 'light french beige',
 'light goldenrod yellow',
 'light gray',
 'light green',
 'light orange',
 'light periwinkle',
 'light pink',
 'light salmon',
 'light sea green',
 'light sky blue',
 'light slate gray',
 'light steel blue',
 'light yellow',
 'lilac',
 'lilac luster',
 'lime (color wheel)',
 'lime (web) (x11 green)',
 'lime green',
 'lincoln green',
 'linen',
 'lion',
 'liseran purple',
 'little boy blue',
 'liver',
 'liver (dogs)',
 'liver (organ)',
 'liver chestnut',
 'livid',
 'macaroni and cheese',
 'madder lake',
 'magenta',
 'magenta (crayola)',
 'magenta (dye)',
 'magenta (pantone)',
 'magenta (process)',
 'magenta haze',
 'magic mint',
 'magnolia',
 'mahogany',
 'maize',
 'maize (crayola)',
 'majorelle blue',
 'malachite',
 'manatee',
 'mandarin',
 'mango',
 'mango tango',
 'mantis',
 'mardi gras',
 'marigold',
 'maroon (crayola)',
 'maroon (web)',
 'maroon (x11)',
 'mauve',
 'mauve taupe',
 'mauvelous',
 'maximum blue',
 'maximum blue green',
 'maximum blue purple',
 'maximum green',
 'maximum green yellow',
 'maximum purple',
 'maximum red',
 'maximum red purple',
 'maximum yellow',
 'maximum yellow red',
 'may green',
 'maya blue',
 'medium aquamarine',
 'medium blue',
 'medium candy apple red',
 'medium carmine',
 'medium champagne',
 'medium orchid',
 'medium purple',
 'medium sea green',
 'medium slate blue',
 'medium spring green',
 'medium turquoise',
 'medium violet-red',
 'mellow apricot',
 'mellow yellow',
 'melon',
 'metallic gold',
 'metallic seaweed',
 'metallic sunburst',
 'mexican pink',
 'middle blue',
 'middle blue green',
 'middle blue purple',
 'middle grey',
 'middle green',
 'middle green yellow',
 'middle purple',
 'middle red',
 'middle red purple',
 'middle yellow',
 'middle yellow red',
 'midnight',
 'midnight blue',
 'midnight green (eagle green)',
 'mikado yellow',
 'mimi pink',
 'mindaro',
 'ming',
 'minion yellow',
 'mint',
 'mint cream',
 'mint green',
 'misty moss',
 'misty rose',
 'mode beige',
 'mona lisa',
 'morning blue',
 'moss green',
 'mountain meadow',
 'mountbatten pink',
 'msu green',
 'mulberry',
 'mulberry (crayola)',
 'mustard',
 'myrtle green',
 'mystic',
 'mystic maroon',
 'nadeshiko pink',
 'naples yellow',
 'navajo white',
 'navy blue',
 'navy blue (crayola)',
 'neon blue',
 'neon carrot',
 'neon green',
 'neon fuchsia',
 'new york pink',
 'nickel',
 'non-photo blue',
 'nyanza',
 'ocean blue',
 'ocean green',
 'ochre',
 'old burgundy',
 'old gold',
 'old lace',
 'old lavender',
 'old mauve',
 'old rose',
 'old silver',
 'olive',
 'olive drab (#3)',
 'olive drab #7',
 'olive green',
 'olivine',
 'onyx',
 'opal',
 'opera mauve',
 'orange',
 'orange (crayola)',
 'orange (pantone)',
 'orange (web)',
 'orange peel',
 'orange-red',
 'orange-red (crayola)',
 'orange soda',
 'orange-yellow',
 'orange-yellow (crayola)',
 'orchid',
 'orchid pink',
 'orchid (crayola)',
 'outer space (crayola)',
 'outrageous orange',
 'oxblood',
 'oxford blue',
 'ou crimson red',
 'pacific blue',
 'pakistan green',
 'palatinate purple',
 'pale aqua',
 'pale cerulean',
 'pale dogwood',
 'pale pink',
 'pale purple (pantone)',
 'pale silver',
 'pale spring bud',
 'pansy purple',
 'paolo veronese green',
 'papaya whip',
 'paradise pink',
 'parchment',
 'paris green',
 'pastel pink',
 'patriarch',
 'paua',
 "payne's grey",
 'peach',
 'peach (crayola)',
 'peach puff',
 'pear',
 'pearly purple',
 'periwinkle',
 'periwinkle (crayola)',
 'permanent geranium lake',
 'persian blue',
 'persian green',
 'persian indigo',
 'persian orange',
 'persian pink',
 'persian plum',
 'persian red',
 'persian rose',
 'persimmon',
 'pewter blue',
 'phlox',
 'phthalo blue',
 'phthalo green',
 'picotee blue',
 'pictorial carmine',
 'piggy pink',
 'pine green',
 'pine tree',
 'pink',
 'pink (pantone)',
 'pink flamingo',
 'pink lace',
 'pink lavender',
 'pink sherbet',
 'pistachio',
 'platinum',
 'plum',
 'plum (web)',
 'plump purple',
 'polished pine',
 'pomp and power',
 'popstar',
 'portland orange',
 'powder blue',
 'princeton orange',
 'process yellow',
 'prune',
 'prussian blue',
 'psychedelic purple',
 'puce',
 'pullman brown (ups brown)',
 'pumpkin',
 'purple',
 'purple (web)',
 'purple (munsell)',
 'purple (x11)',
 'purple mountain majesty',
 'purple navy',
 'purple pizzazz',
 'purple plum',
 'purpureus',
 'queen blue',
 'queen pink',
 'quick silver',
 'quinacridone magenta',
 'radical red',
 'raisin black',
 'rajah',
 'raspberry',
 'raspberry glace',
 'raspberry rose',
 'raw sienna',
 'raw umber',
 'razzle dazzle rose',
 'razzmatazz',
 'razzmic berry',
 'rebecca purple',
 'red',
 'red (crayola)',
 'red (munsell)',
 'red (ncs)',
 'red (pantone)',
 'red (pigment)',
 'red (ryb)',
 'red-orange',
 'red-orange (crayola)',
 'red-orange (color wheel)',
 'red-purple',
 'red salsa',
 'red-violet',
 'red-violet (crayola)',
 'red-violet (color wheel)',
 'redwood',
 'resolution blue',
 'rhythm',
 'rich black',
 'rich black (fogra29)',
 'rich black (fogra39)',
 'rifle green',
 'robin egg blue',
 'rocket metallic',
 'rojo spanish red',
 'roman silver',
 'rose',
 'rose bonbon',
 'rose dust',
 'rose ebony',
 'rose madder',
 'rose pink',
 'rose pompadour',
 'rose quartz',
 'rose red',
 'rose taupe',
 'rose vale',
 'rosewood',
 'rosso corsa',
 'rosy brown',
 'royal blue (dark)',
 'royal blue (light)',
 'royal purple',
 'royal yellow',
 'ruber',
 'rubine red',
 'ruby',
 'ruby red',
 'rufous',
 'russet',
 'russian green',
 'russian violet',
 'rust',
 'rusty red',
 'sacramento state green',
 'saddle brown',
 'safety orange',
 'safety orange (blaze orange)',
 'safety yellow',
 'saffron',
 'sage',
 "st. patrick's blue",
 'salmon',
 'salmon pink',
 'sand',
 'sand dune',
 'sandy brown',
 'sap green',
 'sapphire',
 'sapphire blue',
 'sapphire (crayola)',
 'satin sheen gold',
 'scarlet',
 'schauss pink',
 'school bus yellow',
 "screamin' green",
 'sea green',
 'sea green (crayola)',
 'seance',
 'seal brown',
 'seashell',
 'secret',
 'selective yellow',
 'sepia',
 'shadow',
 'shadow blue',
 'shamrock green',
 'sheen green',
 'shimmering blush',
 'shiny shamrock',
 'shocking pink',
 'shocking pink (crayola)',
 'sienna',
 'silver',
 'silver (crayola)',
 'silver (metallic)',
 'silver chalice',
 'silver pink',
 'silver sand',
 'sinopia',
 'sizzling red',
 'sizzling sunrise',
 'skobeloff',
 'sky blue',
 'sky blue (crayola)',
 'sky magenta',
 'slate blue',
 'slate gray',
 'slimy green',
 'smitten',
 'smoky black',
 'snow',
 'solid pink',
 'sonic silver',
 'space cadet',
 'spanish bistre',
 'spanish blue',
 'spanish carmine',
 'spanish gray',
 'spanish green',
 'spanish orange',
 'spanish pink',
 'spanish red',
 'spanish sky blue',
 'spanish violet',
 'spanish viridian',
 'spring bud',
 'spring frost',
 'spring green',
 'spring green (crayola)',
 'star command blue',
 'steel blue',
 'steel pink',
 'steel teal',
 'stil de grain yellow',
 'straw',
 'strawberry',
 'strawberry blonde',
 'sugar plum',
 'sunglow',
 'sunray',
 'sunset',
 'super pink',
 'sweet brown',
 'syracuse orange',
 'tan',
 'tan (crayola)',
 'tangerine',
 'tango pink',
 'tart orange',
 'taupe',
 'taupe gray',
 'tea green',
 'tea rose',
 'teal',
 'teal blue',
 'telemagenta',
 'tenné (tawny)',
 'terra cotta',
 'thistle',
 'thulian pink',
 'tickle me pink',
 'tiffany blue',
 'timberwolf',
 'titanium yellow',
 'tomato',
 'tourmaline',
 'tropical rainforest',
 'true blue',
 'trypan blue',
 'tufts blue',
 'tumbleweed',
 'turquoise',
 'turquoise blue',
 'turquoise green',
 'turtle green',
 'tuscan',
 'tuscan brown',
 'tuscan red',
 'tuscan tan',
 'tuscany',
 'twilight lavender',
 'tyrian purple',
 'ua blue',
 'ua red',
 'ultramarine',
 'ultramarine blue',
 'ultra pink',
 'ultra red',
 'umber',
 'unbleached silk',
 'united nations blue',
 'university of pennsylvania red',
 'unmellow yellow',
 'up forest green',
 'up maroon',
 'upsdell red',
 'uranian blue',
 'usafa blue',
 'van dyke brown',
 'vanilla',
 'vanilla ice',
 'vegas gold',
 'venetian red',
 'verdigris',
 'vermilion',
 'vermilion',
 'veronica',
 'violet',
 'violet (color wheel)',
 'violet (crayola)',
 'violet (ryb)',
 'violet (web)',
 'violet-blue',
 'violet-blue (crayola)',
 'violet-red',
 'violet-red(perbang)',
 'viridian',
 'viridian green',
 'vivid burgundy',
 'vivid sky blue',
 'vivid tangerine',
 'vivid violet',
 'volt',
 'warm black',
 'weezy blue',
 'wheat',
 'white',
 'wild blue yonder',
 'wild orchid',
 'wild strawberry',
 'wild watermelon',
 'windsor tan',
 'wine',
 'wine dregs',
 'winter sky',
 'wintergreen dream',
 'wisteria',
 'wood brown',
 'xanadu',
 'xanthic',
 'xanthous',
 'yale blue',
 'yellow',
 'yellow (crayola)',
 'yellow (munsell)',
 'yellow (ncs)',
 'yellow (pantone)',
 'yellow (process)',
 'yellow (ryb)',
 'yellow-green',
 'yellow-green (crayola)',
 'yellow-green (color wheel)',
 'yellow orange',
 'yellow orange (color wheel)',
 'yellow sunshine',
 'yinmn blue',
 'zaffre',
 'zomp',
 'gray']


size_list = ['M','W','S','L','XL','N','XS','XXL','D','XXS','XXW','XX','S/M','L/XL','M/L','XS/S','XXXL','XL/REG',
            'M/REG','L/REG','S/REG','REG','XS/REG']

size_word = ['MEDIUM','WIDE','REGULAR','NARROW','SMALL','EXTRA','LARGE']